all: L30

L30: L30_main.cpp L30_ukf.cpp
	g++ -I../src/Eigen -o $@ L30_main.cpp L30_ukf.cpp; ./$@

L27: L27_main.cpp L27_ukf.cpp
	g++ -I../src/Eigen -o $@ L27_main.cpp L27_ukf.cpp; ./$@

L23: L23_main.cpp L23_ukf.cpp
	g++ -I../src/Eigen -o $@ L23_main.cpp L23_ukf.cpp; ./$@

L21: L21_main.cpp L21_ukf.cpp
	g++ -I../src/Eigen -o $@ L21_main.cpp L21_ukf.cpp; ./$@

L18: L18_main.cpp L18_ukf.cpp
	g++ -I../src/Eigen -o $@ L18_main.cpp L18_ukf.cpp; ./$@

L15: L15_main.cpp L15_ukf.cpp
	g++ -I../src/Eigen -o $@ L15_main.cpp L15_ukf.cpp; ./$@

L1x: L15_main.cpp L15_ukf.cpp
	g++ -I../src/Eigen $< -o $@; ./$@

